create table netology.CUSTOMERS
(
    id int generated by default as identity primary key,
    name varchar not null,
    surname varchar not null,
    age int     not null,
    phone_number varchar not null
);

insert into netology.CUSTOMERS (name, surname, age, phone_number)
values ('MAX', 'ORLOV', 33, +1111111111);

insert into netology.CUSTOMERS (name, surname, age, phone_number)
values ('IVAN', 'RASKATOV', 35, +222222222);

insert into netology.CUSTOMERS (name, surname, age, phone_number)
values ('IRINA', 'NIKOLAEVA', 30, +333333333);